name: pubtator
dependencies:
- beautifulsoup4=4.5.1
- enum34=1.1.6
- future=0.16.0
- futures=3.0.3
- lxml=3.7.2
- matplotlib=1.5.3
- numpy=1.11.1 
- pandas=0.18.1 
- scipy=0.18.1  
- sqlalchemy=1.1.4
- pip:
    - tqdm==4.11.2
